"""
Django settings for MaltaCProject project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'te$0((j%_v_hnnb1p_99hj(^j6u*j+gqa(0f1*0psv7v#boeex'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['up201404380.pythonanywhere.com',
				'localhost', 'maltacompanhia.herokuapp.com']

AUTH_USER_MODEL = 'utilizadores.BaseUser'

# Application definition

INSTALLED_APPS = [
	'WebSite',
	'WebSite.tools',
    'WebSite.utilizadores',
    'WebSite.administrador',
    'WebSite.events',
    'WebSite.products',
    'WebSite.cart',
	'WebSite.blog',
	'WebSite.purchase',
    'WebSite.store',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'django_user_agents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django_user_agents.middleware.UserAgentMiddleware',

]

ROOT_URLCONF = 'MaltaCProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MaltaCProject.wsgi.application'



# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
#DATABASES = {
#DB exemplo:
#	'default': {
    #    'ENGINE': 'django.db.backends.mysql',
        #'NAME': 'MaltaC',
        #'USER': 'mysqlDBUser',
        #'PASSWORD': 'maltaDBpassword',
        #'HOST': 'mysql',
	#'HOST': '127.0.0.0',
        #'PORT': '3306',
		#}

db = {
	'default': {
	        'ENGINE': 'django.db.backends.mysql',
	        'NAME': 'MaltaC',
	        'USER': 'mysqlDBUser',
	        'PASSWORD': 'maltaDBpassword',
	        #'HOST': 'mysql',
			'HOST': 'localhost',
	        'PORT': '3306',
	}
}
try:
	if(os.environ['DEPLOY'] == 'production'):
		db = {
			'default': {
		        'ENGINE': 'django.db.backends.postgresql_psycopg2',
		        'NAME': 'd3l9d9paek7ba5',
		        'USER': 'oxflntdgpqgvcg',
		        'PASSWORD': 'e020f81d0095ef01c785bddf87f72678dda5a30db9532fc1da6bd042d2b35ddf',
		        'HOST': 'ec2-54-247-166-129.eu-west-1.compute.amazonaws.com',
		        'PORT': '5432',
	    	}
		}
except KeyError:
	print("Not in deployment")

DATABASES = db
#Server de teste que esta a hospedar
	#'default': {
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': 'up201404380$MaltaC',
    #    'USER': 'up201404380',
    #    'PASSWORD': 'maltaDBpassword',
    #    'HOST': 'up201404380.mysql.pythonanywhere-services.com',
    #    'PORT': '',
	#	}




# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'PT-PT'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    #'/var/www/static/',
]
STATIC_ROOT = os.path.join(BASE_DIR, "static_root")
MEDIA_ROOT = os.path.join(BASE_DIR,"media")
MEDIA_URL = "/media/"

STRIPE_API_KEY = 'sk_test_wdTC5l62o0trBTbQKGGox311'

EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'malta.companhia.dev@gmail.com'
SERVER_EMAIL = 'malta.companhia.dev@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'malta.companhia.dev@gmail.com'
EMAIL_HOST_PASSWORD = 'malta6ninjas'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
